--- #YAML:1.0
name:               WWW-CBF
version:            0.01
abstract:           Brazilian Football Championship status
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:    0
    Web::Scraper:  0.28
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
